Vfront/Controllers/ElastislideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vfront.Controllers
{
    public class ElastislideController : Controller
    {
        //
        // GET: /Elastislide/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index2()
        {
            return View();
        }
        public ActionResult Index3()
        {
            return View();
        }

        public ActionResult Index4()
        {
            return View();
        }
    }
}

Vfront/Views/Elastislide/Index.cshtml
@{
    ViewBag.Title = "Elastislide Demo";
}

<h2>Elastislide Demo 1</h2>
<div class="container demo-1">
            <div class="main">
					<h1>Elastislide <span>A Responsive Image Carousel</span></h1>
					<nav class="nav">
						@Html.ActionLink("Demo 1", "Index", "Elastislide")
						@Html.ActionLink("Demo 2", "Index2", "Elastislide")
						@Html.ActionLink("Demo 3", "Index3", "Elastislide")
						@Html.ActionLink("Demo 4", "Index4", "Elastislide")
					</nav>
				<!-- Elastislide Carousel -->
				<ul id="carousel" class="elastislide-list">
					<li><a href="#"><img src="/content/img/small/1.jpg" alt="image01" /></a></li>
					<li><a href="#"><img src="img/small/2.jpg" alt="image02" /></a></li>
					<li><a href="#"><img src="img/small/3.jpg" alt="image03" /></a></li>
					<li><a href="#"><img src="img/small/4.jpg" alt="image04" /></a></li>
					<li><a href="#"><img src="img/small/5.jpg" alt="image05" /></a></li>
					<li><a href="#"><img src="img/small/6.jpg" alt="image06" /></a></li>
					<li><a href="#"><img src="img/small/7.jpg" alt="image07" /></a></li>
					<li><a href="#"><img src="img/small/8.jpg" alt="image08" /></a></li>
					<li><a href="#"><img src="img/small/9.jpg" alt="image09" /></a></li>
					<li><a href="#"><img src="img/small/10.jpg" alt="image10" /></a></li>
					<li><a href="#"><img src="img/small/11.jpg" alt="image11" /></a></li>
					<li><a href="#"><img src="img/small/12.jpg" alt="image12" /></a></li>
					<li><a href="#"><img src="img/small/13.jpg" alt="image13" /></a></li>
					<li><a href="#"><img src="img/small/14.jpg" alt="image14" /></a></li>
					<li><a href="#"><img src="img/small/15.jpg" alt="image15" /></a></li>
					<li><a href="#"><img src="img/small/16.jpg" alt="image16" /></a></li>
					<li><a href="#"><img src="img/small/17.jpg" alt="image17" /></a></li>
					<li><a href="#"><img src="img/small/18.jpg" alt="image18" /></a></li>
					<li><a href="#"><img src="img/small/19.jpg" alt="image19" /></a></li>
					<li><a href="#"><img src="img/small/20.jpg" alt="image20" /></a></li>
				</ul>
				<!-- End Elastislide Carousel -->

				<p><strong>Resize the browser to see how the carousel adapts</strong></p>

				<p class="info"><strong>Example 1:</strong> A minimum of 3 (default) images are always visible.</p>
			</div>
		</div>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		@section loadResources{
		       @Scripts.Render("~/bundles/elastislide")
 
		}
		<script type="text/javascript">
			
			$( '#carousel' ).elastislide();
			
		</script>

Vfront/Views/Elastislide/Index2.cshtml
@{
    ViewBag.Title = "Elastislide Demo";
}

<h2>Elastislide Demo 2</h2>
		<div class="container demo-2">
            <div class="main clearfix">
					<h1>Elastislide <span>A Responsive Image Carousel</span></h1>
					<nav class="nav">
						@Html.ActionLink("Demo 1", "Index", "Elastislide")
						@Html.ActionLink("Demo 2", "Index2", "Elastislide")
						@Html.ActionLink("Demo 3", "Index3", "Elastislide")
						@Html.ActionLink("Demo 4", "Index4", "Elastislide")
					</nav>
				<div class="column">
					<!-- Elastislide Carousel -->
					<ul id="carousel" class="elastislide-list">
						<li><a href="#"><img src="images/small/4.jpg" alt="image04" /></a></li>
						<li><a href="#"><img src="images/small/5.jpg" alt="image05" /></a></li>
						<li><a href="#"><img src="images/small/6.jpg" alt="image06" /></a></li>
						<li><a href="#"><img src="images/small/7.jpg" alt="image07" /></a></li>
						<li><a href="#"><img src="images/small/11.jpg" alt="image11" /></a></li>
						<li><a href="#"><img src="images/small/12.jpg" alt="image12" /></a></li>
						<li><a href="#"><img src="images/small/13.jpg" alt="image13" /></a></li>
						<li><a href="#"><img src="images/small/14.jpg" alt="image14" /></a></li>
						<li><a href="#"><img src="images/small/15.jpg" alt="image15" /></a></li>
						<li><a href="#"><img src="images/small/16.jpg" alt="image16" /></a></li>
						<li><a href="#"><img src="images/small/17.jpg" alt="image17" /></a></li>
						<li><a href="#"><img src="images/small/18.jpg" alt="image18" /></a></li>
						<li><a href="#"><img src="images/small/19.jpg" alt="image19" /></a></li>
						<li><a href="#"><img src="images/small/20.jpg" alt="image20" /></a></li>
						<li><a href="#"><img src="images/small/1.jpg" alt="image01" /></a></li>
						<li><a href="#"><img src="images/small/2.jpg" alt="image02" /></a></li>
						<li><a href="#"><img src="images/small/3.jpg" alt="image03" /></a></li>
						<li><a href="#"><img src="images/small/8.jpg" alt="image08" /></a></li>
						<li><a href="#"><img src="images/small/9.jpg" alt="image09" /></a></li>
						<li><a href="#"><img src="images/small/10.jpg" alt="image10" /></a></li>
					</ul>
					<!-- End Elastislide Carousel -->
				</div>

				<div class="column">
					<p><strong>Resize the browser to see how the carousel adapts</strong></p>
					<p class="info"><strong>Example 2:</strong> Vertical with a minimum of 3 items visible (automatic height).</p>
				</div>

			</div>
		</div>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript" src="js/jquerypp.custom.js"></script>
		<script type="text/javascript" src="js/jquery.elastislide.js"></script>
		<script type="text/javascript">
			
			$( '#carousel' ).elastislide( {
				orientation : 'vertical'
			} );
			
		</script>

Vfront/Views/Elastislide/Index3.cshtml
@model dynamic

@{
    ViewBag.Title = "Elastislide Demo";
}

<h2>Elastislide Demo 3</h2>
		<div class="container demo-2">
            <div class="main clearfix">
					<h1>Elastislide <span>A Responsive Image Carousel</span></h1>
					<nav class="nav">
						@Html.ActionLink("Demo 1", "Index", "Elastislide")
						@Html.ActionLink("Demo 2", "Index2", "Elastislide")
						@Html.ActionLink("Demo 3", "Index3", "Elastislide")
						@Html.ActionLink("Demo 4", "Index4", "Elastislide")
					</nav>


				<div class="fixed-bar">
					<!-- Elastislide Carousel -->
					<ul id="carousel" class="elastislide-list">
						<li><a href="#"><img src="images/small/1.jpg" alt="image01" /></a></li>
						<li><a href="#"><img src="images/small/2.jpg" alt="image02" /></a></li>
						<li><a href="#"><img src="images/small/3.jpg" alt="image03" /></a></li>
						<li><a href="#"><img src="images/small/4.jpg" alt="image04" /></a></li>
						<li><a href="#"><img src="images/small/5.jpg" alt="image05" /></a></li>
						<li><a href="#"><img src="images/small/6.jpg" alt="image06" /></a></li>
						<li><a href="#"><img src="images/small/7.jpg" alt="image07" /></a></li>
						<li><a href="#"><img src="images/small/8.jpg" alt="image08" /></a></li>
						<li><a href="#"><img src="images/small/9.jpg" alt="image09" /></a></li>
						<li><a href="#"><img src="images/small/10.jpg" alt="image10" /></a></li>
						<li><a href="#"><img src="images/small/11.jpg" alt="image11" /></a></li>
						<li><a href="#"><img src="images/small/12.jpg" alt="image12" /></a></li>
						<li><a href="#"><img src="images/small/13.jpg" alt="image13" /></a></li>
						<li><a href="#"><img src="images/small/14.jpg" alt="image14" /></a></li>
						<li><a href="#"><img src="images/small/15.jpg" alt="image15" /></a></li>
						<li><a href="#"><img src="images/small/16.jpg" alt="image16" /></a></li>
						<li><a href="#"><img src="images/small/17.jpg" alt="image17" /></a></li>
						<li><a href="#"><img src="images/small/18.jpg" alt="image18" /></a></li>
						<li><a href="#"><img src="images/small/19.jpg" alt="image19" /></a></li>
						<li><a href="#"><img src="images/small/20.jpg" alt="image20" /></a></li>
					</ul>
					<!-- End Elastislide Carousel -->
				</div>

				<p><strong>Resize the browser to see how the carousel adapts</strong></p>

				<p class="info"><strong>Example 3:</strong> Fixed wrapper with a minimum of 2 images is always visible.</p>
			</div>
		</div>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript" src="js/jquerypp.custom.js"></script>
		<script type="text/javascript" src="js/jquery.elastislide.js"></script>
		<script type="text/javascript">
			
			$( '#carousel' ).elastislide( {
				minItems : 2
			} );
			
		</script>

Vfront/Views/Elastislide/Index4.cshtml
@{
    ViewBag.Title = "Elastislide Demo";
}

<h2>Elastislide Demo 4</h2>
		<div class="container demo-2">
            <div class="main clearfix">
					<h1>Elastislide <span>A Responsive Image Carousel</span></h1>
					<nav class="nav">
						@Html.ActionLink("Demo 1", "Index", "Elastislide")
						@Html.ActionLink("Demo 2", "Index2", "Elastislide")
						@Html.ActionLink("Demo 3", "Index3", "Elastislide")
						@Html.ActionLink("Demo 4", "Index4", "Elastislide")
					</nav>

				<div class="gallery">
					<!-- Elastislide Carousel -->
					<ul id="carousel" class="elastislide-list">
						<li data-preview="images/large/4.jpg"><a href="#"><img src="images/small/4.jpg" alt="image04" /></a></li>
						<li data-preview="images/large/5.jpg"><a href="#"><img src="images/small/5.jpg" alt="image05" /></a></li>
						<li data-preview="images/large/6.jpg"><a href="#"><img src="images/small/6.jpg" alt="image06" /></a></li>
						<li data-preview="images/large/7.jpg"><a href="#"><img src="images/small/7.jpg" alt="image07" /></a></li>
						<li data-preview="images/large/11.jpg"><a href="#"><img src="images/small/11.jpg" alt="image11" /></a></li>
						<li data-preview="images/large/12.jpg"><a href="#"><img src="images/small/12.jpg" alt="image12" /></a></li>
						<li data-preview="images/large/13.jpg"><a href="#"><img src="images/small/13.jpg" alt="image13" /></a></li>
						<li data-preview="images/large/14.jpg"><a href="#"><img src="images/small/14.jpg" alt="image14" /></a></li>
						<li data-preview="images/large/15.jpg"><a href="#"><img src="images/small/15.jpg" alt="image15" /></a></li>
						<li data-preview="images/large/16.jpg"><a href="#"><img src="images/small/16.jpg" alt="image16" /></a></li>
						<li data-preview="images/large/17.jpg"><a href="#"><img src="images/small/17.jpg" alt="image17" /></a></li>
						<li data-preview="images/large/18.jpg"><a href="#"><img src="images/small/18.jpg" alt="image18" /></a></li>
						<li data-preview="images/large/19.jpg"><a href="#"><img src="images/small/19.jpg" alt="image19" /></a></li>
						<li data-preview="images/large/20.jpg"><a href="#"><img src="images/small/20.jpg" alt="image20" /></a></li>
						<li data-preview="images/large/1.jpg"><a href="#"><img src="images/small/1.jpg" alt="image01" /></a></li>
						<li data-preview="images/large/2.jpg"><a href="#"><img src="images/small/2.jpg" alt="image02" /></a></li>
						<li data-preview="images/large/3.jpg"><a href="#"><img src="images/small/3.jpg" alt="image03" /></a></li>
						<li data-preview="images/large/8.jpg"><a href="#"><img src="images/small/8.jpg" alt="image08" /></a></li>
						<li data-preview="images/large/9.jpg"><a href="#"><img src="images/small/9.jpg" alt="image09" /></a></li>
						<li data-preview="images/large/10.jpg"><a href="#"><img src="images/small/10.jpg" alt="image10" /></a></li>
					</ul>
					<!-- End Elastislide Carousel -->

					<div class="image-preview">
						<img id="preview" src="images/large/4.jpg" />
					</div>
				</div>

				<p><strong>Resize the browser to see how the carousel adapts</strong></p>
				<p class="info"><strong>Example 4:</strong> Usage in an image gallery; a minimum of 4 images are visible.</p>

			</div>
		</div>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript" src="js/jquerypp.custom.js"></script>
		<script type="text/javascript" src="js/jquery.elastislide.js"></script>
		<script type="text/javascript">
			
			// example how to integrate with a previewer

			var current = 0,
				$preview = $( '#preview' ),
				$carouselEl = $( '#carousel' ),
				$carouselItems = $carouselEl.children(),
				carousel = $carouselEl.elastislide( {
					current : current,
					minItems : 4,
					onClick : function( el, pos, evt ) {

						changeImage( el, pos );
						evt.preventDefault();

					},
					onReady : function() {

						changeImage( $carouselItems.eq( current ), current );
						
					}
				} );

			function changeImage( el, pos ) {

				$preview.attr( 'src', el.data( 'preview' ) );
				$carouselItems.removeClass( 'current-img' );
				el.addClass( 'current-img' );
				carousel.setCurrent( pos );

			}

		</script>